name:        pairing
version:     1.1.0
synopsis:    Bilinear pairings
description: Bilinear pairings over elliptic curves
maintainer:  Adjoint Inc (info@adjoint.io)
license:     MIT
github:      adjoint-io/pairing
category:    Cryptography

default-extensions:
  - LambdaCase
  - RecordWildCards
  - OverloadedStrings
  - NoImplicitPrelude
  - FlexibleInstances
  - FlexibleContexts
  - ScopedTypeVariables
  - RankNTypes
  - ConstraintKinds
  - DataKinds
  - DeriveGeneric
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedLists
  - PatternSynonyms
  - TypeFamilyDependencies

dependencies:
  - base             >= 4.10   && < 5
  - protolude        >= 0.2    && < 0.3
  - bytestring       >= 0.10.8 && < 0.11
  - elliptic-curve   >= 0.3    && < 0.4
  - errors           >= 2.3.0  && < 2.4
  - galois-field     >= 1.0.3  && < 2.0
  - groups           >= 0.4.1  && < 0.5
  - MonadRandom      >= 0.5.1  && < 0.6
  - tasty-quickcheck >= 0.10.1 && < 0.11

extra-source-files:
  - README.notex.md
  - ChangeLog.md

ghc-options:
  - -freverse-errors
  - -O2
  - -Wall

library:
  exposed-modules:
    - Data.Pairing
    - Data.Pairing.Ate
    - Data.Pairing.BLS12381
    - Data.Pairing.BN254
    - Data.Pairing.BN254A
    - Data.Pairing.BN254B
    - Data.Pairing.BN254C
    - Data.Pairing.BN254D
    - Data.Pairing.BN462
    - Data.Pairing.Hash
  source-dirs:
    - src

tests:
  pairing-tests:
    main: Main
    dependencies:
      - pairing
      - QuickCheck
      - quickcheck-instances
      - tasty
      - tasty-hunit
      - tasty-quickcheck
    source-dirs:
      - test

  example-tests:
    main: Example.hs
    dependencies:
      - pairing

benchmarks:
  pairing-benchmarks:
    main: Main
    dependencies:
      - criterion
      - pairing
    source-dirs:
      - bench
