resolver: lts-14.16
extra-deps:
  - elliptic-curve-0.3.0
  - git: https://github.com/adjoint-io/galois-field.git
    commit: ad82cd2d626ad54a2c3c6cd1c62c31ab4e5ab2c1
  - poly-0.4.0.0
  - semirings-0.5.3
  - vector-algorithms-0.8.0.3
  - mod-0.1.1.0
  - bitvec-1.0.3.0
  - QuickCheck-2.13.2
